trim:
  prefixAll:
  - FSRM_
  - dwMD
  - pbMD
  - TPMVSC_
  - TPMVSCMGR_
  - IWRM
  - FrsRpc
  - Frs
  - PFRS_
  - Rdc
  - RDC_
  - NtFrsApi_Rpc_
  - FRS_RDC
  - FRS
  - ITpm
  - bMD
  - pmdrMD
  - szMD
  - pszMD
  - pdwMD
  - pftMD
  - hMD
  - cchMD
  - pcchMD
  - Fsrm
  - IFsrm
  - CprepDisk
  - Cprep
  - IClusCfg
  - WdsRpc
  - W32TIME_
  - W32Time
  - TsProxy
  - TSG_
  - TSG
  - RemoteSP
  - WITNESS_
  - Witnessr
  - SC_RPC_
  - SERVICE_RPC_
  - SC_
  - Wsdr
  - NSI_
  - I_nsi_
  - WINSINTF_
  - R_Wins
  - AUTHZ_
  - AUTHZR_
  - Authzr
  - Authz
  - IRPCAsyncNotify_
  - IRPCRemoteObject_
  - PrintAsyncNotify
  - PrintAsync
  - RpcAsync
  - RpcIpp
  - RRPC_FW
  - EvtRpc
  - R_Dnssrv
  - DNS_RPC
  - DNSSRV_RPC
  - DNSSRV
  - DNS
  - RRP
  - R_Dhcp
  - DHCP
  - Dhcp
  - NetrWksta
  - NetrLogon
  - NetrServer
  - NetrDfs
  - DFSM_
  - FSF_
  - DFS_
  - Dfs
  - Netr
  - Netpr
  - Nspi
  - NSPI_
  - VDS_
  - VDS
  - __VDS_
  - IVds
  - WBEM_
  - _WBEM
  - IWbem
  - Wbem
  - Dsr
  - Lsar
  - ept
  - Samr
  - IDL_DRS
  - DRS
  - IDL_DSA
  - IDL_
  - DSA
  - LSAPR_
  - LSAP_
  - LSA_
  - Lsap
  - RPC_FAX_
  - RPC
  - I_Browserr
  - DsRoler
  - DsRole
  - DSROLER
  - DSROLE
  - NLPR_
  - NETLOGON_
  - Netlogon
  - NL_
  - Elfr
  - IELF
  - m_guid
  - m_pwsz
  - m_pwz
  - m_g
  - m_ll
  - m_
  - _vd
  - _td
  - VT_
  - JOINPR_
  - SchRpc
  - CLUSDSK_
  - SAMPR_
  - SAMR_
  - TRK_
  - TRKWKS_
  - TRKSVR_
  - Lnk
  - Ee
  - FW_
  - FAX_ENUM_
  - FAX_
  - FaxObs_
  - FSSAGENT_
  - R_InetInfo
  - R_QM
  - rpc_AC
  - rpc_QM
  - R_
  - INET_INFO
  - INETA_
  - RpcNetEvent
  - S_DS
  - S_
  - srv_h
  - cli_p
  - RemoteQM
  - RemoteQm
  - Rfr
  - EcR
  - Ec
  - multiSz
  - PerflibV2
  - EFS_RPC
  - EFS_
  - EfsRpc
  - Efs
  - IMSMQ
  - MSMQ
  - pUnk
  - psMSMQ
  - pbstrGuid
  - bstrGuid
  - ppqinfo
  - Rasrpc
  - RASRPC_
  - RasRpc
  - RRasAdmin
  - RMprAdmin
  - DIM_
  - MPRAPI_
  - MPRI_
  - MPR_
  - RB_PCB
  - RB_
  - IC_
  - IS_
  - IMGID_
  - IMGOD_
  - IA_
  - IB_
  - GC_
  - RI_
  - P_
  - NTMS_
  - INtms
  - VSS_
  - IVss
  - rpc__mgmt
  - conv_
  - convc_
  - CV_OUT_
  - CV_
  - CVR_
  - CVRC_
